services:
  upstream:
    image: jcchavezs/httpmole:latest
    ports:
      - 10080:10080
    volumes:
      - .:/conf
    command: [ "-response-file", "/conf/response.json" ]

  envoy:
    depends_on:
      - upstream
    image: ${ENVOY_IMAGE:-envoyproxy/envoy:v1.23-latest}
    command:
      - -c
      - /conf/envoy-config.yaml
      - --log-level
      - info
      - --component-log-level
      - wasm:debug
      - --log-format [%Y-%m-%d %T.%f][%t][%l][%n] [%g:%#] %v
      - --log-path
      - /home/envoy/logs/envoy.log
    volumes:
      - ./build:/build
      - .:/conf
      - ./logs:/home/envoy/logs:rw
    ports:
      - 8080:8080
      - 8082:8082
